<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <ProjectReference Include="..\Modules.Backup.Application\Modules.Backup.Application.csproj"/>
        <ProjectReference Include="..\Modules.Backup.Infrastructure\Modules.Backup.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
