<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
        <PackageReference Include="MimeKit" Version="4.14.0" />
        <PackageReference Include="MailKit" Version="4.14.0" />
        <PackageReference Include="MySqlConnector" Version="2.4.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="SSH.NET" Version="2025.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AuthModule\Modules.Auth.Core\Modules.Auth.Core.csproj"/>
        <ProjectReference Include="..\..\AuthModule\Modules.Auth.Infrastructure\Modules.Auth.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\CryptoModule\Modules.Crypto.Shared\Modules.Crypto.Shared.csproj"/>
        <ProjectReference Include="..\Modules.Backup.Core\Modules.Backup.Core.csproj"/>
        <ProjectReference Include="..\Modules.Backup.Infrastructure\Modules.Backup.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
