<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="OneOf" Version="3.0.271"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Attributes\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AdministrationModule\Modules.Administration.Shared\Modules.Administration.Shared.csproj"/>
        <ProjectReference Include="..\..\AuthModule\Modules.Auth.Shared\Modules.Auth.Shared.csproj"/>
    </ItemGroup>

</Project>
