<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Modules.Shared\Modules.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Testcontainers" Version="4.8.1" />
      <PackageReference Include="Testcontainers.MsSql" Version="4.8.1" />
      <PackageReference Include="Testcontainers.MySql" Version="4.8.1" />
      <PackageReference Include="Testcontainers.PostgreSql" Version="4.8.1" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MySqlConnector">
        <HintPath>..\..\..\..\..\..\..\..\.nuget\packages\mysqlconnector\2.4.0\lib\net9.0\MySqlConnector.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
